# Generated by Django 4.2.5 on 2023-09-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_messages_alter_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
