# Generated by Django 4.2.5 on 2023-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Drinks', 'Drinks'), ('Breakfast', 'Breakfast')], default='Dinner'),
        ),
    ]
