# Generated by Django 4.2.6 on 2023-10-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_recipe_recipe_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Drinks', 'Drinks'), ('Dessert', 'Dessert')], default='Dinner'),
        ),
    ]
