# Generated by Django 4.2.6 on 2023-10-31 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_cuisine_remove_recipe_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.cuisine')),
                ('ingredient', models.ManyToManyField(to='foodapp.ingredient')),
            ],
        ),
    ]
