# Generated by Django 4.2.6 on 2023-11-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_galleryimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImages',
            new_name='GalleryImage',
        ),
    ]
